# Generated by Django 3.0.8 on 2020-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('None', 'Select a category'), ('fashion', 'Fashion'), ('eletronics', 'Eletronics & DIY'), ('personal care', 'Personal Care'), ('furniture', 'Furniture & Appliances')], default='None', max_length=22),
        ),
        migrations.AlterField(
            model_name='auction',
            name='bids',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startingBid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
