# Generated by Django 3.0.8 on 2020-08-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200831_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='state',
        ),
        migrations.AddField(
            model_name='listing',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.URLField(max_length=300),
        ),
    ]
