# Generated by Django 3.0.8 on 2020-08-31 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200831_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='bids',
            new_name='bid',
        ),
    ]
