# Generated by Django 3.0.8 on 2020-08-31 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200831_2317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction',
            new_name='Bid',
        ),
    ]
