# Generated by Django 3.0.8 on 2020-09-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('None', 'Select a category'), ('Fashion', 'Fashion'), ('Eletronics & DIY', 'Eletronics & DIY'), ('Personal Care', 'Personal Care'), ('Furniture & Appliances', 'Furniture & Appliances')], default='None', max_length=22),
        ),
    ]
